//buy app
POST http://localhost:5000/api/apps/646a53f0b53851cda14d10b9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDY4N2IxY2ExNjUzYTA0MWEwMDBhNDkiLCJ3aXNobGlzdCI6W10sImZpcnN0TmFtZSI6IkZpcnN0IiwibGFzdE5hbWUiOiJMYXN0IiwiZW1haWwiOiJhQGEuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkWGUzUzBRR09lak50bktRR2FnMFcwLlZ6UjNqc3FGalN6SzAzL2NOTkpwZk5WR1g4bGYxZ2kiLCJkYXRlQ3JlYXRlZCI6IjIwMjMtMDUtMjBUMDc6NDc6MzguMDE3WiIsImZyb3plbiI6ZmFsc2UsIl9fdiI6MCwiaWF0IjoxNjg0NzEzODM4LCJleHAiOjE2ODQ4MDAyMzh9.1WEz2dUixzgnG68ArZqdX0ktNaMie17c82D7pVwXKVI
Content-Type: application/json

{
  
}

###

//register a user
POST http://localhost:5000/api/user/register
Content-Type: application/json

{
"firstName": "First",
"lastName": "Last",
"email": "a@a.com",
"password": "pass"
}

###

//login a user
POST http://localhost:5000/api/user/login
Content-Type: application/json

{
  "email": "a@a.com",
  "password": "pass"
}

###

//search for an app

GET http://localhost:5000/api/search/test
Content-Type: application/json

{

}

###

//get user purchases

GET http://localhost:5000/api/user/purchases
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDY4N2IxY2ExNjUzYTA0MWEwMDBhNDkiLCJ3aXNobGlzdCI6W10sImZpcnN0TmFtZSI6IkZpcnN0IiwibGFzdE5hbWUiOiJMYXN0IiwiZW1haWwiOiJhQGEuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkWGUzUzBRR09lak50bktRR2FnMFcwLlZ6UjNqc3FGalN6SzAzL2NOTkpwZk5WR1g4bGYxZ2kiLCJkYXRlQ3JlYXRlZCI6IjIwMjMtMDUtMjBUMDc6NDc6MzguMDE3WiIsImZyb3plbiI6ZmFsc2UsIl9fdiI6MCwiaWF0IjoxNjg0NTY5MTA3LCJleHAiOjE2ODQ2NTU1MDd9.iVQOFqKJujFARz-5ouKnVEQ8DwkSlPGt-t6NeJM7HgQ
Content-Type: application/json

{
  
}

###

//create a new app

POST http://localhost:5000/api/app/create
Content-Type: application/json

{
  "name": "Grand Theft Auto: San Andreas",
  "desc": "Five years ago, Carl Johnson escaped from the pressures of life in Los Santos, San Andreas, a city tearing itself apart with gang trouble, drugs and corruption. Where filmstars and millionaires do their best to avoid the dealers and gangbangers. Now, it’s the early 90’s. Carl’s got to go home. His mother has been murdered, his family has fallen apart and his childhood friends are all heading towards disaster.",
  "publisher": "Rockstar Games",
  "category": "Games",
  "price": 799,
  "imgNames": ["gtasa1","gtasa2"]
}